[build-system]
requires = ["setuptools>=42", "cython", "flake8", "pytest>=5.4", "pytest-cov",
            "pytest-runner", "setuptools_scm[toml]>=3.4", "wheel", "sphinx",
            "sphinx-autodoc-annotation", ]

[tool.setuptools_scm]
