resultsdir: "$HOME/tmp/resultsdir"

database:
    url: "postgresql://devtest@localhost/devtest"
    # url: "sqlite:///var/tmp/devtest.db"

flags:
    debug: 0
    verbose: 0
    keep: 0
    stderr: 0
    repeat: 1

uiautomator:
    google:
        runner: "com.github.uiautomator.test/androidx.test.runner.AndroidJUnitRunner"
        apks:
            - "apks/app_uiautomator.apk"
            - "apks/app_uiautomator_test.apk"
    upstream:
        runner: "com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner"
        apks:
            - "apks/app-uiautomator.apk"
            - "apks/app-uiautomator-test.apk"

webui:
    static_folder: "/var/www/devtest/static"
    secret_key: "sKlSkwdtEstbdlKD94$$kldspCwLdkkDAld"
    auth_username: "admin"
    auth_password: "devtest"
    realm: "devtest"
    redis_url: "redis://localhost:6379/0"

roles:
    displayer:
        package: "com.google.android.apps.photos"
        intent: ".home.HomeActivity"
        destdir: "/sdcard/Pictures"  # TODO(dart) query device
        images:  # ResultType to image
            CONTACT:
                "/google/src/files/head/depot/google3/lens/testing/tests/lenslite_datasets/english_business_card.png"
