resultsdir: "$HOME/tmp/resultsdir"

database:
    select: "local"
    local:
        url: "postgresql://devtest@localhost/devtest"

flags:
    debug: 0
    verbose: 0
    keep: 0
    stderr: 0
    repeat: 1

uiautomator:
    upstream:
        runner: "com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner"
        apks:
            - "apks/app-uiautomator.apk"
            - "apks/app-uiautomator-test.apk"

roles: {}
